version: '3.8'

services:
  wibeslam-agent:
    build: .
    image: wibeslam:latest
    container_name: wibeslam_agent
    network_mode: "host"
    privileged: true
    volumes:
      - /dev:/dev
    environment:
      - MODE=udp
      - DEVICE=/dev/ttyACM0
    restart: unless-stopped